//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeTalk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeTalk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more queries, please mail us at .
        /// </summary>
        public static string AboutMoreInfo {
            get {
                return ResourceManager.GetString("AboutMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalk is a Visual Studio plugin that improves IDE accessibility for screen reader users..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About CodeTalk.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalk Key Selection.
        /// </summary>
        public static string CodeTalkKeyAutomationText {
            get {
                return ResourceManager.GetString("CodeTalkKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalk Key.
        /// </summary>
        public static string CodeTalkKeyText {
            get {
                return ResourceManager.GetString("CodeTalkKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalk Modifier Key Selection.
        /// </summary>
        public static string CodeTalkModifierAutomationText {
            get {
                return ResourceManager.GetString("CodeTalkModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalk Modifier Key.
        /// </summary>
        public static string CodeTalkModifierText {
            get {
                return ResourceManager.GetString("CodeTalkModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalk.
        /// </summary>
        public static string CodeTalkString {
            get {
                return ResourceManager.GetString("CodeTalkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has syntax errors. Please fix them and try again..
        /// </summary>
        public static string CompilationErrorMessage {
            get {
                return ResourceManager.GetString("CompilationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Breakpoint.
        /// </summary>
        public static string ContinueAutomationText {
            get {
                return ResourceManager.GetString("ContinueAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Breakpoint.
        /// </summary>
        public static string ContinueCheckBoxText {
            get {
                return ResourceManager.GetString("ContinueCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TalkPoint.
        /// </summary>
        public static string CreateAutomationText {
            get {
                return ResourceManager.GetString("CreateAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TalkPoint.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Errors Command Key.
        /// </summary>
        public static string ErrorListKey {
            get {
                return ResourceManager.GetString("ErrorListKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Errors Command Key Selection.
        /// </summary>
        public static string ErrorListKeyAutomationText {
            get {
                return ResourceManager.GetString("ErrorListKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Errors Command Modifier Key Selection.
        /// </summary>
        public static string ErrorListModifierAutomationText {
            get {
                return ResourceManager.GetString("ErrorListModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Errors Command Modifier Key.
        /// </summary>
        public static string ErrorListModifierText {
            get {
                return ResourceManager.GetString("ErrorListModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Errors Command.
        /// </summary>
        public static string ErrorListText {
            get {
                return ResourceManager.GetString("ErrorListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of errors.
        /// </summary>
        public static string ErrorListTitle {
            get {
                return ResourceManager.GetString("ErrorListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButtonText {
            get {
                return ResourceManager.GetString("ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process code file due to an internal error.
        /// </summary>
        public static string FileProcessError {
            get {
                return ResourceManager.GetString("FileProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Summary.
        /// </summary>
        public static string FileSummaryAutomation {
            get {
                return ResourceManager.GetString("FileSummaryAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File summary.
        /// </summary>
        public static string FileSummaryTitle {
            get {
                return ResourceManager.GetString("FileSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Functions Command Modifier Key Selection.
        /// </summary>
        public static string FunctionsListModifierAutomationText {
            get {
                return ResourceManager.GetString("FunctionsListModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Functions Command Modifier Key.
        /// </summary>
        public static string FunctionsListModifierText {
            get {
                return ResourceManager.GetString("FunctionsListModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Functions Command.
        /// </summary>
        public static string FunctionsListText {
            get {
                return ResourceManager.GetString("FunctionsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of functions.
        /// </summary>
        public static string FunctionsListTitle {
            get {
                return ResourceManager.GetString("FunctionsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Context Command Key.
        /// </summary>
        public static string GetContextKey {
            get {
                return ResourceManager.GetString("GetContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Context Command Key Selection.
        /// </summary>
        public static string GetContextKeyAutomationText {
            get {
                return ResourceManager.GetString("GetContextKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Context Command Modifier Key Selection.
        /// </summary>
        public static string GetContextModifierAutomationText {
            get {
                return ResourceManager.GetString("GetContextModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Context Command Modifier Key.
        /// </summary>
        public static string GetContextModifierText {
            get {
                return ResourceManager.GetString("GetContextModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Context Command.
        /// </summary>
        public static string GetContextText {
            get {
                return ResourceManager.GetString("GetContextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current context.
        /// </summary>
        public static string GetContextTitle {
            get {
                return ResourceManager.GetString("GetContextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Functions Command Key Selection.
        /// </summary>
        public static string GetFunctionsKeyAutomationText {
            get {
                return ResourceManager.GetString("GetFunctionsKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Functions Command Key.
        /// </summary>
        public static string GetFunctionsKeyText {
            get {
                return ResourceManager.GetString("GetFunctionsKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Summary Command Key.
        /// </summary>
        public static string GetSummaryKey {
            get {
                return ResourceManager.GetString("GetSummaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Summary Command Key Selection.
        /// </summary>
        public static string GetSummaryKeyAutomationText {
            get {
                return ResourceManager.GetString("GetSummaryKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Summary Command Modifier Key Selection.
        /// </summary>
        public static string GetSummaryModifierAutomationText {
            get {
                return ResourceManager.GetString("GetSummaryModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Summary Command Modifier Key.
        /// </summary>
        public static string GetSummaryModifierText {
            get {
                return ResourceManager.GetString("GetSummaryModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Summary Command.
        /// </summary>
        public static string GetSummaryText {
            get {
                return ResourceManager.GetString("GetSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Context Command Key Selection.
        /// </summary>
        public static string MoveToContextKeyAutomation {
            get {
                return ResourceManager.GetString("MoveToContextKeyAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Context Command Key.
        /// </summary>
        public static string MoveToContextKeyText {
            get {
                return ResourceManager.GetString("MoveToContextKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Context Command Modifier Key selection.
        /// </summary>
        public static string MoveToContextModifierAutomation {
            get {
                return ResourceManager.GetString("MoveToContextModifierAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Context Command Modifier Key.
        /// </summary>
        public static string MoveToContextModifierText {
            get {
                return ResourceManager.GetString("MoveToContextModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Context Command.
        /// </summary>
        public static string MoveToContextText {
            get {
                return ResourceManager.GetString("MoveToContextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No context found in line.
        /// </summary>
        public static string NoContextString {
            get {
                return ResourceManager.GetString("NoContextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors found..
        /// </summary>
        public static string NoErrorsString {
            get {
                return ResourceManager.GetString("NoErrorsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No functions found..
        /// </summary>
        public static string NoFunctionsString {
            get {
                return ResourceManager.GetString("NoFunctionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OptionsCancelText {
            get {
                return ResourceManager.GetString("OptionsCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string OptionsSubmitText {
            get {
                return ResourceManager.GetString("OptionsSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeTalkOptions.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and cookies.
        /// </summary>
        public static string PrivacyButtonText {
            get {
                return ResourceManager.GetString("PrivacyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Comment Command Key.
        /// </summary>
        public static string SkipCommentKey {
            get {
                return ResourceManager.GetString("SkipCommentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Comment Command Key Selection.
        /// </summary>
        public static string SkipCommentKeyAutomationText {
            get {
                return ResourceManager.GetString("SkipCommentKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Comment Command Modifier Key Selection.
        /// </summary>
        public static string SkipCommentModifierAutomationText {
            get {
                return ResourceManager.GetString("SkipCommentModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Comment Command Modifier Key.
        /// </summary>
        public static string SkipCommentModifierText {
            get {
                return ResourceManager.GetString("SkipCommentModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Comment Command.
        /// </summary>
        public static string SkipCommentText {
            get {
                return ResourceManager.GetString("SkipCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression or Statement (required).
        /// </summary>
        public static string StatementAutomation {
            get {
                return ResourceManager.GetString("StatementAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TalkPoint Command Key Selection.
        /// </summary>
        public static string TalkPointKeyAutomationText {
            get {
                return ResourceManager.GetString("TalkPointKeyAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TalkPoint Command Key.
        /// </summary>
        public static string TalkPointKeyText {
            get {
                return ResourceManager.GetString("TalkPointKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TalkPoint Command Modifier Key Selection.
        /// </summary>
        public static string TalkPointModifierAutomationText {
            get {
                return ResourceManager.GetString("TalkPointModifierAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TalkPoint Command Modifier Key.
        /// </summary>
        public static string TalkPointModifierText {
            get {
                return ResourceManager.GetString("TalkPointModifierText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select talkpoint type (required).
        /// </summary>
        public static string TalkPointSelectAutomation {
            get {
                return ResourceManager.GetString("TalkPointSelectAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Talkpoint type *.
        /// </summary>
        public static string TalkPointSelectAutomationTextBox {
            get {
                return ResourceManager.GetString("TalkPointSelectAutomationTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression\Statement *.
        /// </summary>
        public static string TalkpointStatementTextBox {
            get {
                return ResourceManager.GetString("TalkpointStatementTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TalkPoint Command.
        /// </summary>
        public static string TalkPointText {
            get {
                return ResourceManager.GetString("TalkPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tone *.
        /// </summary>
        public static string TalkpointToneSelectTextBox {
            get {
                return ResourceManager.GetString("TalkpointToneSelectTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Breakpoint.
        /// </summary>
        public static string TalkPointWindowTitle {
            get {
                return ResourceManager.GetString("TalkPointWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tone (required).
        /// </summary>
        public static string ToneSelectAutomation {
            get {
                return ResourceManager.GetString("ToneSelectAutomation", resourceCulture);
            }
        }
    }
}
