//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeTalk.Drawiz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Drawiz.IImageParsingService")]
    public interface IImageParsingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageParsingService/ParseImageBytes", ReplyAction="http://tempuri.org/IImageParsingService/ParseImageBytesResponse")]
        string ParseImageBytes(byte[] bytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageParsingService/ParseImageBytes", ReplyAction="http://tempuri.org/IImageParsingService/ParseImageBytesResponse")]
        System.Threading.Tasks.Task<string> ParseImageBytesAsync(byte[] bytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageParsingService/ParseImageFile", ReplyAction="http://tempuri.org/IImageParsingService/ParseImageFileResponse")]
        string ParseImageFile(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageParsingService/ParseImageFile", ReplyAction="http://tempuri.org/IImageParsingService/ParseImageFileResponse")]
        System.Threading.Tasks.Task<string> ParseImageFileAsync(System.IO.Stream stream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageParsingServiceChannel : Microsoft.CodeTalk.Drawiz.IImageParsingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageParsingServiceClient : System.ServiceModel.ClientBase<Microsoft.CodeTalk.Drawiz.IImageParsingService>, Microsoft.CodeTalk.Drawiz.IImageParsingService {
        
        public ImageParsingServiceClient() {
        }
        
        public ImageParsingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageParsingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageParsingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageParsingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ParseImageBytes(byte[] bytes) {
            return base.Channel.ParseImageBytes(bytes);
        }
        
        public System.Threading.Tasks.Task<string> ParseImageBytesAsync(byte[] bytes) {
            return base.Channel.ParseImageBytesAsync(bytes);
        }
        
        public string ParseImageFile(System.IO.Stream stream) {
            return base.Channel.ParseImageFile(stream);
        }
        
        public System.Threading.Tasks.Task<string> ParseImageFileAsync(System.IO.Stream stream) {
            return base.Channel.ParseImageFileAsync(stream);
        }
    }
}
